name: Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  docker:
    uses: cellpointdigital/github-reusable-workflows/.github/workflows/docker-build.yml@main
    with:
      image_name: pgbouncer
